# Generated by Django 5.2.17 on 2026-08-11 15:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('time', models.CharField(help_text='Example: 9:00 AM - 5:00 PM', max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Workshop', 'Workshop'), ('Competition', 'Competition'), ('Hackathon', 'Hackathon'), ('Science Fair', 'Science Fair'), ('Seminar', 'Seminar'), ('Exhibition', 'Exhibition'), ('Training', 'Training'), ('Robotics', 'Robotics'), ('AI', 'AI'), ('Coding', 'Coding'), ('Engineering', 'Engineering'), ('Other', 'Other')], default='Other', max_length=50)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='events/posters/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='events/banners/')),
                ('description', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('registration_open', models.BooleanField(default=True)),
                ('achievements', models.CharField(blank=True, max_length=255, null=True)),
                ('participant_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('comment', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='events/testimonials/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('school', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='EventVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video', models.FileField(blank=True, null=True, upload_to='events/videos/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='events/video-thumbnails/')),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='events.event')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
